src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups("list")
     * @Groups("task")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255,unique=true)
     * @Groups("list")
     * @Groups("task")
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     * @Groups("list")
     * @Groups("task")
     */
    private $started_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups("list")
     * @Groups("task")
     */
    private $ended_at;
    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("list")
     * @Groups("task")
     */
    private $statut;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Task", mappedBy="project")
     * @Groups("task")
     */
    private $tasks;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeInterface $started_at): self
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeInterface
    {
        return $this->ended_at;
    }

    public function setEndedAt(?\DateTimeInterface $ended_at): self
    {
        $this->ended_at = $ended_at;

        return $this;
    }
    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }


    /**
     * @return Collection|Task[]
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks[] = $task;
            $task->setProject($this);
        }

        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->tasks->contains($task)) {
            $this->tasks->removeElement($task);
            // set the owning side to null (unless already changed)
            if ($task->getProject() === $this) {
                $task->setProject(null);
            }
        }

        return $this;
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Entity\Task;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\AddProjectType;
use App\Form\ChangeStatutType;

class ProjectController extends AbstractController
{
    /**
     * @Route("/admin-projects", name="admin-projects")
     */
    public function listProject()
    {
        $projectRepository=$this->getDoctrine()->getRepository(Project::class);
        $projects=$projectRepository->findAll();
        $taskRepository=$this->getDoctrine()->getRepository(Task::class);
        $countTasks=$taskRepository->getCountByProject();
        return $this->render('project/index.html.twig', [
            'projects' => $projects,
            'countTasks'=>$countTasks
        ]);
    }
    /**
     * @Route("/admin-add-project", name="admin-add-project")
     */
    public function addProject(Request $request)
    {
        $project = new Project();
        $date= new \DateTime();
        $form= $this->createForm(AddProjectType::class,$project);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $project->setStartedAt($date);
            $project->setStatut("Nouveau");
            $this->getDoctrine()->getManager()->persist($project);
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('admin-projects');
        }
        return $this->render('project/addProject.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/admin-project/{id}", name="admin-project")
     */
    public function detailProject($id,Request $request){
        $projectRepository=$this->getDoctrine()->getRepository(Project::class);
        $project=$projectRepository->findOneBy(['id'=>$id]);
        $taskRepository=$this->getDoctrine()->getRepository(Task::class);
        $tasks=$taskRepository->getTasksByProject($id);
        $countTasks=$taskRepository->getCountByProject();
        $form= $this->createForm(ChangeStatutType::class,$project);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            if($project->getStatut()=="Terminé"){
                $date=new \DateTime();
                $project->setEndedAt($date);
            }
            $this->getDoctrine()->getManager()->persist($project);
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('admin-project',['id' => $project->getId()]);
        }
        return $this->render('project/detailProject.html.twig', [
            'project' => $project,
            'tasks' => $tasks,
            'form' => $form->createView(),
            'countTasks'=>$countTasks

        ]);
    }
}

templates/project/addProject.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projects{% endblock %}

{% block body %}
<h2 class="text-center">Ajouter un projet</h2>
{{form(form)}}
{% endblock %}

templates/project/detailProject.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail projet{% endblock %}

{% block body %}
<h2 class="text-center">Détail du projet : {{project.name}}</h2>
<p>Crée le : {{project.startedAt|date("d/m/Y")}}</p>
{% set nbreTasks = 0 %}
      {% for countTask in countTasks %}
        {% if countTask['id'] == project.id %}
          {% set nbreTasks = countTask['nbrTasks'] %}
        {% endif %}
      {% endfor %}
<p>Nombre de tâches : {{nbreTasks}}</p>
{% if project.statut != "Terminé" %}
<a href="{{ path('admin-add-task',{'id':project.getId()}) }}" class="btn btn-outline-success m-2">Ajouter une tâche</a>
{{form(form)}}
{% endif %}
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nom de la tâche</th>
      <th scope="col">Description</th>
      <th scope="col">Ajouté le</th>
    </tr>
  </thead>
  <tbody>
  {% for task in tasks %}
    <tr>
      <td>{{task.title}}</td>
      <td>{{task.description}}</td>
      <td>{{task.getCreatedAt()|date("d/m/Y")}}</td>    
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projects{% endblock %}

{% block body %}
<h2 class="text-center">Projets</h2>
<a href="{{ path('admin-add-project') }}" class="btn btn-outline-success m-2">Ajouter un projet</a>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Nom du projet</th>
      <th scope="col">Statut</th>
      <th scope="col">Tâches</th>
      <th scope="col">Ajouté le</th>
      <th scope="col">Terminé le</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  {% for project in projects %}
    <tr>
      <td>{{project.name}}</td>
      <td>{{project.statut}}</td>
      {% set nbreTasks = 0 %}
      {% for countTask in countTasks %}
        {% if countTask['id'] == project.id %}
          {% set nbreTasks = countTask['nbrTasks'] %}
        {% endif %}
      {% endfor %}
      <td>{{nbreTasks}}</td>      
      <td>{{project.getStartedAt()|date("d/m/Y")}}</td>
      {% if project.getEndedAt() == null %}
      <td>Non fini</td>
      {% else %}
      <td>{{project.getEndedAt()|date("d/m/Y")}}</td>
      {% endif %}
      <td><a href="{{path('admin-project',{'id':project.getId()})}}">Gérer</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}